# version: '3'
# services:
#   ui-react:
#     build: 
#       context: ./my-app
#       dockerfile: Dockerfile
#     container_name: ui-react
#     ports:
#       - "3000:3000"
#     networks:
#       - mern-stack-network
#   back-react:
#     build:
#       context: ./Back-end
#       dockerfile: Dockerfile
#     container_name: back-react
#     ports:
#       - "4000:4000"
#     networks:
#       - mern-stack-network
# networks:
#   mern-stack-network:


version: '3'
services:
  ui-react:
    build: 
      context: ./my-app
      dockerfile: Dockerfile
    container_name: ui-react
    ports:
      - "3000:3000"
    networks:
      - mern-stack-network
    depends_on:
      - mongo
  back-react:
    build:
      context: ./Back-end
      dockerfile: Dockerfile
    container_name: back-react
    ports:
      - "4000:4000"
    networks:
      - mern-stack-network
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mern-stack-network
networks:
  mern-stack-network:
    driver: bridge
volumes:
  mongodb_data:
